#!/usr/bin/env bash
# Shared helpers for Copland LAIN installers.
# SPDX-License-Identifier: Apache-2.0
# shellcheck shell=bash

COPLAND_STATE_DIR="${COPLAND_STATE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/copland-lain}"
COPLAND_MANIFEST="${COPLAND_MANIFEST:-$COPLAND_STATE_DIR/install-manifest}"

# Repo root = parent of scripts/ (install.sh lives at repo root and sources via scripts/lib)
if [[ -z "${REPO_ROOT:-}" ]]; then
  _lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  REPO_ROOT="$(cd "$_lib_dir/../.." && pwd)"
fi

COPLAND_DRY_RUN="${COPLAND_DRY_RUN:-0}"
COPLAND_VERBOSE="${COPLAND_VERBOSE:-0}"
COPLAND_SKIP_TOOLS="${COPLAND_SKIP_TOOLS:-0}"

# $USER is not set in every environment (su, cron, minimal shells).
COPLAND_TARGET_USER="${USER:-$(id -un)}"

# Manifest accumulators (newline-separated lists)
MANIFEST_FILES=""
MANIFEST_PACKAGES=""
MANIFEST_TOOLS_INSTALLED=""
MANIFEST_TOOLS_SKIPPED=""
MANIFEST_TOOLS_CONFLICT=""

log()  { printf '%s\n' "$*"; }
err()  { printf 'error: %s\n' "$*" >&2; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

verbose() {
  if [[ "${COPLAND_VERBOSE}" == "1" ]]; then
    printf 'verbose: %s\n' "$*" >&2
  fi
}

refuse_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    die "Refusing to run as root. Run as the Plasma user whose ~/.local should receive configs."
  fi
}

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1
}

manifest_add() {
  # manifest_add <section> <value>
  local section="$1"
  local value="$2"
  case "$section" in
    files) MANIFEST_FILES+="${value}"$'\n' ;;
    packages) MANIFEST_PACKAGES+="${value}"$'\n' ;;
    tools_installed) MANIFEST_TOOLS_INSTALLED+="${value}"$'\n' ;;
    tools_skipped) MANIFEST_TOOLS_SKIPPED+="${value}"$'\n' ;;
    tools_conflict) MANIFEST_TOOLS_CONFLICT+="${value}"$'\n' ;;
    *) die "unknown manifest section: $section" ;;
  esac
}

_manifest_uniq_lines() {
  # stdin -> unique non-empty lines
  awk 'NF && !seen[$0]++'
}

write_manifest() {
  local dest="${1:-$COPLAND_MANIFEST}"
  if [[ "${COPLAND_DRY_RUN}" == "1" ]]; then
    log "dry-run: would write manifest → $dest"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  {
    printf '# Copland LAIN install manifest\n'
    printf '# Generated by install.sh — used by uninstall.sh\n'
    printf 'version=1\n'
    printf 'home=%s\n' "$HOME"
    printf 'timestamp=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '\n[files]\n'
    printf '%s' "$MANIFEST_FILES" | _manifest_uniq_lines
    printf '\n[packages]\n'
    printf '%s' "$MANIFEST_PACKAGES" | _manifest_uniq_lines
    printf '\n[tools_installed]\n'
    printf '%s' "$MANIFEST_TOOLS_INSTALLED" | _manifest_uniq_lines
    printf '\n[tools_skipped]\n'
    printf '%s' "$MANIFEST_TOOLS_SKIPPED" | _manifest_uniq_lines
    printf '\n[tools_conflict]\n'
    printf '%s' "$MANIFEST_TOOLS_CONFLICT" | _manifest_uniq_lines
  } >"$dest"
  verbose "wrote manifest $dest"
}

# Read a [section] from an existing manifest into a variable name.
# manifest_read_section <file> <section> <varname>
manifest_read_section() {
  local file="$1"
  local section="$2"
  local -n _out="$3"
  _out=""
  [[ -f "$file" ]] || return 1
  local in=0
  local line
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == "[$section]" ]]; then
      in=1
      continue
    fi
    if [[ "$line" == \[*\] ]]; then
      in=0
      continue
    fi
    if [[ "$in" -eq 1 && -n "$line" && "$line" != \#* ]]; then
      _out+="${line}"$'\n'
    fi
  done <"$file"
}

wallpaper_pkg_dir() {
  printf '%s\n' "$REPO_ROOT/packages/plasma/wallpapers/org.lainavi.copland.scene"
}

desktoptheme_pkg_dir() {
  printf '%s\n' "$REPO_ROOT/packages/plasma/desktoptheme/org.lainavi.copland"
}

aurorae_pkg_dir() {
  printf '%s\n' "$REPO_ROOT/packages/aurorae/themes/org.lainavi.copland"
}

colors_src() {
  printf '%s\n' "$REPO_ROOT/packages/color-schemes/CoplandLain.colors"
}

fonts_src_dir() {
  printf '%s\n' "$REPO_ROOT/packages/plasma/wallpapers/org.lainavi.copland.scene/contents/ui/scene/assets/fonts"
}
