#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate Copland LAIN Aurorae SVG theme assets.

Edit the palette / glyphs here, then run from the repo root:

    python3 tools/generate-aurorae.py

Committed SVGs under packages/aurorae/themes/org.lainavi.copland/ are what
KWin installs — this script is the single edit path so the nine button files
and decoration.svg stay in sync.

Fills are hardcoded scene hexes (not Plasma ColorScheme classes). ColorScheme
remapping previously turned inactive chrome white; brand chrome must stay
locked to the wallpaper palette regardless of the active scheme.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEME = ROOT / "packages/aurorae/themes/org.lainavi.copland"
VERSION = "1.2"

# Scene palette (match packages/plasma/.../scene/css/scene.css)
BG = "#040017"
BASE = "#0083bc"
ACCENT = "#000a4f"
HEADER = "#002a7a"
TEXT_BRIGHT = "#e8f6ff"
TEXT_DIM = "#7aa0c0"
HOVER = "#2ab0e0"


def button_svg(glyph_active: str, glyph_inactive: str) -> str:
    """Eight Aurorae button states on a 24×24 grid, strip width 192."""
    states = [
        ("active-center", None, BASE, glyph_active),
        ("hover-center", "translate(24,0)", HOVER, glyph_active),
        ("pressed-center", "translate(48,0)", BASE, glyph_active),
        ("inactive-center", "translate(72,0)", ACCENT, glyph_inactive),
        ("deactivated-center", "translate(96,0)", BG, glyph_inactive),
        ("hover-inactive-center", "translate(120,0)", ACCENT, glyph_inactive),
        ("pressed-inactive-center", "translate(144,0)", BG, glyph_inactive),
        ("deactivated-inactive-center", "translate(168,0)", BG, glyph_inactive),
    ]
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<svg xmlns="http://www.w3.org/2000/svg" width="192" height="24" version="1.1">',
        "  <!-- Generated by tools/generate-aurorae.py — do not hand-edit. -->",
    ]
    for sid, transform, tile, glyph in states:
        tr = f' transform="{transform}"' if transform else ""
        parts.append(f'  <g id="{sid}"{tr}>')
        parts.append(
            f'    <rect x="0" y="0" width="24" height="24" fill="{tile}"/>'
        )
        for line in glyph.strip().splitlines():
            parts.append(f"    {line.strip()}")
        parts.append("  </g>")
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def decoration_svg() -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="280" height="160" version="1.1">
  <!-- Generated by tools/generate-aurorae.py — do not hand-edit. -->

  <rect id="decoration-topleft" x="8" y="8" width="3" height="32" fill="{BASE}"/>
  <g id="decoration-top">
    <rect x="11" y="8" width="48" height="32" fill="{HEADER}"/>
    <rect x="11" y="8" width="48" height="2" fill="{BASE}"/>
    <rect x="11" y="37" width="48" height="3" fill="{BASE}"/>
  </g>
  <rect id="decoration-topright" x="59" y="8" width="3" height="32" fill="{BASE}"/>

  <rect id="decoration-left" x="8" y="40" width="3" height="48" fill="{BASE}"/>
  <rect id="decoration-center" x="11" y="40" width="48" height="48" fill="{BG}"/>
  <rect id="decoration-right" x="59" y="40" width="3" height="48" fill="{BASE}"/>

  <rect id="decoration-bottomleft" x="8" y="88" width="3" height="3" fill="{BASE}"/>
  <rect id="decoration-bottom" x="11" y="88" width="48" height="3" fill="{BASE}"/>
  <rect id="decoration-bottomright" x="59" y="88" width="3" height="3" fill="{BASE}"/>

  <rect id="decoration-inactive-topleft" x="140" y="8" width="3" height="32" fill="{TEXT_DIM}"/>
  <g id="decoration-inactive-top">
    <rect x="143" y="8" width="48" height="32" fill="{ACCENT}"/>
    <rect x="143" y="8" width="48" height="2" fill="{TEXT_DIM}"/>
    <rect x="143" y="37" width="48" height="3" fill="{TEXT_DIM}"/>
  </g>
  <rect id="decoration-inactive-topright" x="191" y="8" width="3" height="32" fill="{TEXT_DIM}"/>
  <rect id="decoration-inactive-left" x="140" y="40" width="3" height="48" fill="{TEXT_DIM}"/>
  <rect id="decoration-inactive-center" x="143" y="40" width="48" height="48" fill="{BG}"/>
  <rect id="decoration-inactive-right" x="191" y="40" width="3" height="48" fill="{TEXT_DIM}"/>
  <rect id="decoration-inactive-bottomleft" x="140" y="88" width="3" height="3" fill="{TEXT_DIM}"/>
  <rect id="decoration-inactive-bottom" x="143" y="88" width="48" height="3" fill="{TEXT_DIM}"/>
  <rect id="decoration-inactive-bottomright" x="191" y="88" width="3" height="3" fill="{TEXT_DIM}"/>

  <g id="decoration-maximized-center">
    <rect x="8" y="120" width="48" height="32" fill="{HEADER}"/>
    <rect x="8" y="149" width="48" height="3" fill="{BASE}"/>
  </g>
  <g id="decoration-maximized-inactive-center">
    <rect x="140" y="120" width="48" height="32" fill="{ACCENT}"/>
    <rect x="140" y="149" width="48" height="3" fill="{TEXT_DIM}"/>
  </g>

  <rect id="hint-stretch-borders" x="1" y="1" width="1" height="1" fill="none"/>
</svg>
"""


def write_metadata() -> None:
    desktop = f"""[Desktop Entry]
Name=Copland LAIN
Comment=Copland / LAIN window decoration matching the wallpaper scene chrome
X-KDE-PluginInfo-Author=WPE_NAVI_LINUX contributors
X-KDE-PluginInfo-Email=
X-KDE-PluginInfo-Name=org.lainavi.copland
X-KDE-PluginInfo-Version={VERSION}
X-KDE-PluginInfo-Website=https://github.com/anotherriblyagervant/WPE_NAVI_LINUX
X-KDE-PluginInfo-Category=
X-KDE-PluginInfo-License=Apache-2.0
X-KDE-PluginInfo-EnabledByDefault=false
"""
    meta_json = f"""{{
    "KPlugin": {{
        "Authors": [
            {{
                "Name": "WPE_NAVI_LINUX contributors"
            }}
        ],
        "Category": "",
        "Description": "Copland / LAIN window decoration matching the wallpaper scene chrome",
        "EnabledByDefault": false,
        "Id": "org.lainavi.copland",
        "License": "Apache-2.0",
        "Name": "Copland LAIN",
        "Version": "{VERSION}",
        "Website": "https://github.com/anotherriblyagervant/WPE_NAVI_LINUX"
    }}
}}
"""
    (THEME / "metadata.desktop").write_text(desktop)
    (THEME / "metadata.json").write_text(meta_json)


def main() -> None:
    THEME.mkdir(parents=True, exist_ok=True)

    ga = TEXT_BRIGHT
    gi = TEXT_DIM

    glyphs = {
        "close.svg": (
            f'<path fill="{ga}" d="M6.2,4.6 L4.6,6.2 L17.8,19.4 L19.4,17.8 Z"/>\n'
            f'<path fill="{ga}" d="M17.8,4.6 L19.4,6.2 L6.2,19.4 L4.6,17.8 Z"/>',
            f'<path fill="{gi}" d="M6.2,4.6 L4.6,6.2 L17.8,19.4 L19.4,17.8 Z"/>\n'
            f'<path fill="{gi}" d="M17.8,4.6 L19.4,6.2 L6.2,19.4 L4.6,17.8 Z"/>',
        ),
        "minimize.svg": (
            f'<rect x="5" y="17" width="14" height="2.5" fill="{ga}"/>',
            f'<rect x="5" y="17" width="14" height="2.5" fill="{gi}"/>',
        ),
        "maximize.svg": (
            f'<path fill="{ga}" fill-rule="evenodd" '
            f'd="M5,5 H19 V19 H5 Z M7.5,7.5 V16.5 H16.5 V7.5 Z"/>',
            f'<path fill="{gi}" fill-rule="evenodd" '
            f'd="M5,5 H19 V19 H5 Z M7.5,7.5 V16.5 H16.5 V7.5 Z"/>',
        ),
        # Two offset rings (evenodd), same style as maximize — no overlapping slab.
        "restore.svg": (
            f'<path fill="{ga}" fill-rule="evenodd" '
            f'd="M8,4 H20 V16 H8 Z M10.5,6.5 V13.5 H17.5 V6.5 Z '
            f'M4,8 H16 V20 H4 Z M6.5,10.5 V17.5 H13.5 V10.5 Z"/>',
            f'<path fill="{gi}" fill-rule="evenodd" '
            f'd="M8,4 H20 V16 H8 Z M10.5,6.5 V13.5 H17.5 V6.5 Z '
            f'M4,8 H16 V20 H4 Z M6.5,10.5 V17.5 H13.5 V10.5 Z"/>',
        ),
        "help.svg": (
            f'<path fill="{ga}" d="M10.2,6.2 C10.2,5 11.2,4.2 12.2,4.2 '
            f"C13.2,4.2 14.2,5 14.2,6.2 C14.2,7.6 12.8,8.2 12.2,9.2 "
            f"L12.2,11.2 L10.8,11.2 L10.8,8.8 C11.4,7.8 12.8,7.4 12.8,6.2 "
            f"C12.8,5.6 12.5,5.4 12.2,5.4 C11.8,5.4 11.6,5.7 11.6,6.2 Z "
            f'M10.8,13.2 L12.4,13.2 L12.4,14.8 L10.8,14.8 Z"/>',
            f'<path fill="{gi}" d="M10.2,6.2 C10.2,5 11.2,4.2 12.2,4.2 '
            f"C13.2,4.2 14.2,5 14.2,6.2 C14.2,7.6 12.8,8.2 12.2,9.2 "
            f"L12.2,11.2 L10.8,11.2 L10.8,8.8 C11.4,7.8 12.8,7.4 12.8,6.2 "
            f"C12.8,5.6 12.5,5.4 12.2,5.4 C11.8,5.4 11.6,5.7 11.6,6.2 Z "
            f'M10.8,13.2 L12.4,13.2 L12.4,14.8 L10.8,14.8 Z"/>',
        ),
        "alldesktops.svg": (
            f'<circle cx="7" cy="12" r="1.6" fill="{ga}"/>'
            f'<circle cx="12" cy="12" r="1.6" fill="{ga}"/>'
            f'<circle cx="17" cy="12" r="1.6" fill="{ga}"/>',
            f'<circle cx="7" cy="12" r="1.6" fill="{gi}"/>'
            f'<circle cx="12" cy="12" r="1.6" fill="{gi}"/>'
            f'<circle cx="17" cy="12" r="1.6" fill="{gi}"/>',
        ),
        "keepabove.svg": (
            f'<path fill="{ga}" d="M5,14 L12,6 L19,14 Z"/>',
            f'<path fill="{gi}" d="M5,14 L12,6 L19,14 Z"/>',
        ),
        "keepbelow.svg": (
            f'<path fill="{ga}" d="M5,10 L12,18 L19,10 Z"/>',
            f'<path fill="{gi}" d="M5,10 L12,18 L19,10 Z"/>',
        ),
        "shade.svg": (
            f'<path fill="{ga}" d="M5,8 L19,8 L19,10 L5,10 Z M5,14 L19,14 L12,20 Z"/>',
            f'<path fill="{gi}" d="M5,8 L19,8 L19,10 L5,10 Z M5,14 L19,14 L12,20 Z"/>',
        ),
    }

    for name, (active, inactive) in glyphs.items():
        (THEME / name).write_text(button_svg(active, inactive))
        print(f"wrote {THEME.relative_to(ROOT) / name}")

    (THEME / "decoration.svg").write_text(decoration_svg())
    print(f"wrote {THEME.relative_to(ROOT) / 'decoration.svg'}")

    write_metadata()
    print(f"wrote metadata Version={VERSION}")


if __name__ == "__main__":
    main()
